name: tryingharder
on: push
jobs:
  ubuntu:
    name: print_linux
    runs-on: ubuntu-latest
    steps: 
      - name: printdate1
        run: date
  windows:
    name: print_win
    runs-on: windows-latest
    steps: 
      - name: printdate2
        run: Get-Date
  macintosh:
    name: print_mac
    runs-on: macos-latest
    steps: 
      - name: printdate3
        run: date
  depends:
   name: print_win_seq
   needs: [job1, job2, job3]
   runs-on: windows-latest
   steps: 
      - name: printdate3
        run: whoami