name: tryingharder
on: push
jobs:
  job1:
    name: print_win
    runs-on: ubuntu-latest
    steps: 
      - name: printdate1
        run: date
  job2:
    name: printdate2
    runs-on: windows-latest
    steps: 
      - name: printdate2
        run: Get-Date
  job3:
    name: printdate3
    runs-on: macos-latest
    steps: 
      - name: printdate3
        run: date
  job4:
   name: printdate4
   needs: [job1, job2, job3]
   runs-on: windows-latest
   steps: 
      - name: printdate3
        run: whoami